<?php

/**
 * @file
 * Contains find a doctor search form.
 *
 * @copyright Copyright (c) 2019 Palantir.net
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Extends hook_form_alter().
 *
 * @param array $form
 *   Form array.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   Form state interface.
 * @param string $form_id
 *   The ID of the form.
 */
function towerhealth_autocomplete_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $id = $form['#id'];

  if ($id == 'views-exposed-form-find-a-provider-find-doctor') {
    $form['find_doctor_search']['#autocomplete_route_name'] = 'towerhealth_autocomplete.autocomplete.finddoctor';
    $form['find_doctor_search']['#attributes']['class'] = ['find-care-autocomplete'];
    $form['find_doctor_search']['#attributes']['placeholder'] = t('Search by Name, Condition or Specialty');
    $form['#attached']['library'][] = 'towerhealth_autocomplete/towerhealth_autocomplete';
  }
  elseif ($id == 'views-exposed-form-find-a-location-find-location') {
    $form['find_location_search']['#autocomplete_route_name'] = 'towerhealth_autocomplete.autocomplete.findlocation';
    $form['find_location_search']['#attributes']['class'] = ['find-care-autocomplete'];
    $form['find_location_search']['#attributes']['placeholder'] = t('Search by Location Name, Condition or Service');
    $form['#attached']['library'][] = 'towerhealth_autocomplete/towerhealth_autocomplete';
  }
  elseif ($id == 'views-exposed-form-find-a-service-find-service') {
    $form['find_services_search']['#autocomplete_route_name'] = 'towerhealth_autocomplete.autocomplete.findservices';
    $form['find_services_search']['#attributes']['class'] = ['find-care-autocomplete'];
    $form['find_services_search']['#attributes']['placeholder'] = t('Search by Condition or Service');
    $form['#attached']['library'][] = 'towerhealth_autocomplete/towerhealth_autocomplete';
  }
  elseif ($id == 'views-exposed-form-search-search-page') {
    $form['site_search']['#autocomplete_route_name'] = 'towerhealth_autocomplete.autocomplete.findservices';
    $form['site_search']['#attributes']['class'] = ['site-search-autocomplete'];
    $form['site_search']['#attributes']['placeholder'] = t('Search site content');
    $form['#attached']['library'][] = 'towerhealth_autocomplete/towerhealth_autocomplete';
  }
}
