<?php

/**
 * @file
 * Contains find a doctor search form.
 *
 * @copyright Copyright (c) 2019 Palantir.net
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Extends hook_form_alter();
 *
 * @param $variables
 */
function towerhealth_autocomplete_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $id = $form['#id'];

  if ($id == 'views-exposed-form-search-page-1') {
    $form['search_api_fulltext']['#autocomplete_route_name'] = 'towerhealth_autocomplete.autocomplete.finddoctor';
  }
}