<?php

/**
 * @file
 * Contains find a doctor search form.
 *
 * @copyright Copyright (c) 2019 Palantir.net
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Extends hook_form_alter().
 *
 * @param array $form
 *   Form array.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   Form state interface.
 * @param string $form_id
 *   The ID of the form.
 */
function towerhealth_autocomplete_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $id = $form['#id'];

  if ($id == 'views-exposed-form-find-a-provider-find-doctor') {
    $form['find_doctor_search']['#autocomplete_route_name'] = 'towerhealth_autocomplete.autocomplete.finddoctor';
  }
}
