<?php

/**
 * @file
 * Contains custom Tower Health code.
 *
 * @copyright Copyright (c) 2019 Palantir.net
 */

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Add custom sort order for find a provider search.
 *
 * @param object\ViewExecutable $view
 *   View to alter.
 * @param object\QueryPluginBase $query
 *   View query.
 */
function towerhealth_misc_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'find_a_provider') {
    // Sort by provider type custom solr field first.
    $query->sort('provider_sort_field', 'ASC');
    // Then sort by relevance.
    $query->sort('search_api_relevance', 'DESC');
    // And finally by name.
    $query->sort('title', 'ASC');
  }
}

/**
 * Form alter exposed view block.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
/*function towerhealth_misc_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  dump($form);
  dump($form_state);
  dump($form_id);
  if ($form['#id'] == 'views-exposed-form-find-a-location-find-location' && in_array('location_latlon', $form)) {
    //unset($form['location_latlon']);
  }
  elseif ($form['#id'] == 'views-exposed-form-find-a-provider-find-doctor' && in_array('location_latlon', $form)) {
    //unset($form['provider_location_latlong']);
  }
}*/