status: '2'
pattern: '[node:field_profile_first_name] [node:field_profile_middle_name] [node:field_profile_last_name], [node:field_profile_professional_title]'
php: 0
escape: 0
dependencies:
  config:
    - node.type.profile
