features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
appointment_phone_number: 484-628-4357
appointment_phone_label: 484-628-HELP
