<?php

use Drupal\migrate\MigrateExecutable;
use Drupal\migrate\MigrateMessage;

/**
 * Cron tasks
 */
function towerhealth_msow_migration_cron() {
  $migrations = [
    'towerhealth_provider_locations_group'
  ];
  foreach($migrations as $migration) {
    $migration = \Drupal::service('plugin.manager.migration')->createInstance($migration);
    
    // If the migration is to be executed using an `--update` flag.
    $migration->getIdMap()->prepareUpdate();
    $executable = new MigrateExecutable($migration, new MigrateMessage());
    $executable->import();
    \Drupal::logger('towerhealth_msow_migration')->notice('Migration group: ' . $migration . ' updated');
  }
}